import groovy.json.JsonSlurper

if(JavaVersion.current() < JavaVersion.VERSION_17){
    throw new GradleException("JDK 17 is a required minimum version. Yours: ${System.getProperty('java.version')}")
}

def modJson = new File(rootDir, 'mod.json')
def modInfo = new JsonSlurper().parseText(modJson.text)

include ':annotations'
include ':main'
include ':tools'

rootProject.name = modInfo.displayName