#\uF8FF
63743=omaloon-cliff|omaloon-cliff-ui
#\uF8FE
63742=omaloon-cliff-helper|omaloon-cliff-helper-ui
#\uF8FD
63741=omaloon-ore-cobalt|omaloon-ore-cobalt-ui
#\uF8FC
63740=omaloon-ore-nickel|omaloon-ore-nickel-ui
#\uF8FB
63739=omaloon-ore-coal|omaloon-ore-coal-ui
#\uF8FA
63738=omaloon-magnetite-large-crystals|omaloon-magnetite-large-crystals-ui
#\uF8F9
63737=omaloon-magnetite-crystals|omaloon-magnetite-crystals-ui
#\uF8F8
63736=omaloon-glasmore-metal|omaloon-glasmore-metal-ui
#\uF8F7
63735=omaloon-glasmore-metal-plus|omaloon-glasmore-metal-plus-ui
#\uF8F6
63734=omaloon-glasmore-metal-don|omaloon-glasmore-metal-don-ui
#\uF8F5
63733=omaloon-ruined-tiles|omaloon-ruined-tiles-ui
#\uF8F4
63732=omaloon-ruined-masonry|omaloon-ruined-masonry-ui
#\uF8F3
63731=omaloon-ruined-wall|omaloon-ruined-wall-ui
#\uF8F2
63730=omaloon-gerb-remains|omaloon-gerb-remains-ui
#\uF8F1
63729=omaloon-dead-grass|omaloon-dead-grass-ui
#\uF8F0
63728=omaloon-dead-shrub|omaloon-dead-shrub-ui
#\uF8EF
63727=omaloon-dead-spike-tree|omaloon-dead-spike-tree-ui
#\uF8EE
63726=omaloon-dead-bush-tree|omaloon-dead-bush-tree-ui
#\uF8ED
63725=omaloon-fallen-dead-tree|omaloon-fallen-dead-tree-ui
#\uF8EC
63724=omaloon-fallen-dead-tree-top-half|omaloon-fallen-dead-tree-top-half-ui
#\uF8EB
63723=omaloon-fallen-dead-tree-bottom-half|omaloon-fallen-dead-tree-bottom-half-ui
#\uF8EA
63722=omaloon-dead-tree|omaloon-dead-tree-ui
#\uF8E9
63721=omaloon-dead-tree-stump|omaloon-dead-tree-stump-ui
#\uF8E8
63720=omaloon-frozen-soil|omaloon-frozen-soil-ui
#\uF8E7
63719=omaloon-frozen-soil-wall|omaloon-frozen-soil-wall-ui
#\uF8E6
63718=omaloon-frozen-soil-boulder|omaloon-frozen-soil-boulder-ui
#\uF8E5
63717=omaloon-alabaster|omaloon-alabaster-ui
#\uF8E4
63716=omaloon-alabaster-tiles|omaloon-alabaster-tiles-ui
#\uF8E3
63715=omaloon-alabaster-craters|omaloon-alabaster-craters-ui
#\uF8E2
63714=omaloon-alabaster-craters-large|omaloon-alabaster-craters-large-ui
#\uF8E1
63713=omaloon-alabaster-wall|omaloon-alabaster-wall-ui
#\uF8E0
63712=omaloon-alabaster-boulder|omaloon-alabaster-boulder-ui
#\uF8DF
63711=omaloon-smooth-aghanite|omaloon-smooth-aghanite-ui
#\uF8DE
63710=omaloon-cracked-aghanite|omaloon-cracked-aghanite-ui
#\uF8DD
63709=omaloon-pebbled-aghanite|omaloon-pebbled-aghanite-ui
#\uF8DC
63708=omaloon-sandy-aghanite|omaloon-sandy-aghanite-ui
#\uF8DB
63707=omaloon-aghanite|omaloon-aghanite-ui
#\uF8DA
63706=omaloon-aghanite-wall|omaloon-aghanite-wall-ui
#\uF8D9
63705=omaloon-aghanite-crag|omaloon-aghanite-crag-ui
#\uF8D8
63704=omaloon-aghanite-boulder|omaloon-aghanite-boulder-ui
#\uF8D7
63703=omaloon-gray-aghanite|omaloon-gray-aghanite-ui
#\uF8D6
63702=omaloon-smooth-gray-aghanite|omaloon-smooth-gray-aghanite-ui
#\uF8D5
63701=omaloon-gray-aghanite-wall|omaloon-gray-aghanite-wall-ui
#\uF8D4
63700=omaloon-gray-aghanite-crag|omaloon-gray-aghanite-crag-ui
#\uF8D3
63699=omaloon-gray-aghanite-boulder|omaloon-gray-aghanite-boulder-ui
#\uF8D2
63698=omaloon-smooth-white-aghanite|omaloon-smooth-white-aghanite-ui
#\uF8D1
63697=omaloon-weathered-white-aghanite|omaloon-weathered-white-aghanite-ui
#\uF8D0
63696=omaloon-white-aghanite|omaloon-white-aghanite-ui
#\uF8CF
63695=omaloon-white-aghanite-dust|omaloon-white-aghanite-dust-ui
#\uF8CE
63694=omaloon-white-aghanite-wall|omaloon-white-aghanite-wall-ui
#\uF8CD
63693=omaloon-white-aghanite-boulder|omaloon-white-aghanite-boulder-ui
#\uF8CC
63692=omaloon-verdant-aghanite|omaloon-verdant-aghanite-ui
#\uF8CB
63691=omaloon-verdant-aghanite-wall|omaloon-verdant-aghanite-wall-ui
#\uF8CA
63690=omaloon-verdant-aghanite-boulder|omaloon-verdant-aghanite-boulder-ui
#\uF8C9
63689=omaloon-deep-glacium|omaloon-deep-glacium-ui
#\uF8C8
63688=omaloon-shallow-glacium|omaloon-shallow-glacium-ui
#\uF8C7
63687=omaloon-grenite-glacium|omaloon-grenite-glacium-ui
#\uF8C6
63686=omaloon-grenite|omaloon-grenite-ui
#\uF8C5
63685=omaloon-coastal-grenite|omaloon-coastal-grenite-ui
#\uF8C4
63684=omaloon-grenite-wall|omaloon-grenite-wall-ui
#\uF8C3
63683=omaloon-dark-grenite-wall|omaloon-dark-grenite-wall-ui
#\uF8C2
63682=omaloon-grenite-boulder|omaloon-grenite-boulder-ui
#\uF8C1
63681=omaloon-blue-ice|omaloon-blue-ice-ui
#\uF8C0
63680=omaloon-blue-ice-pieces|omaloon-blue-ice-pieces-ui
#\uF8BF
63679=omaloon-weathered-ice|omaloon-weathered-ice-ui
#\uF8BE
63678=omaloon-blue-ice-wall|omaloon-blue-ice-wall-ui
#\uF8BD
63677=omaloon-weathered-ice-wall|omaloon-weathered-ice-wall-ui
#\uF8BC
63676=omaloon-blue-snow|omaloon-blue-snow-ui
#\uF8BB
63675=omaloon-blue-snowdrifts|omaloon-blue-snowdrifts-ui
#\uF8BA
63674=omaloon-blue-snow-wall|omaloon-blue-snow-wall-ui
#\uF8B9
63673=omaloon-blue-boulder|omaloon-blue-boulder-ui
#\uF8B8
63672=omaloon-tube-conveyor|omaloon-tube-conveyor-ui
#\uF8B7
63671=omaloon-tube-distributor|omaloon-tube-distributor-ui
#\uF8B6
63670=omaloon-tube-junction|omaloon-tube-junction-ui
#\uF8B5
63669=omaloon-tube-bridge-conveyor|omaloon-tube-bridge-conveyor-ui
#\uF8B4
63668=omaloon-tube-sorter|omaloon-tube-sorter-ui
#\uF8B3
63667=omaloon-tube-overflow-gate|omaloon-tube-overflow-gate-ui
#\uF8B2
63666=omaloon-tube-underflow-gate|omaloon-tube-underflow-gate-ui
#\uF8B1
63665=omaloon-liquid-tube|omaloon-liquid-tube-ui
#\uF8B0
63664=omaloon-liquid-junction|omaloon-liquid-junction-ui
#\uF8AF
63663=omaloon-liquid-bridge|omaloon-liquid-bridge-ui
#\uF8AE
63662=omaloon-liquid-pump|omaloon-liquid-pump-ui
#\uF8AD
63661=omaloon-liquid-outlet|omaloon-liquid-outlet-ui
#\uF8AC
63660=omaloon-composite-press|omaloon-composite-press-ui
#\uF8AB
63659=omaloon-wind-turbine|omaloon-wind-turbine-ui
#\uF8AA
63658=omaloon-coal-generator|omaloon-coal-generator-ui
#\uF8A9
63657=omaloon-impulse-node|omaloon-impulse-node-ui
#\uF8A8
63656=omaloon-hammer-drill|omaloon-hammer-drill-ui
#\uF8A7
63655=omaloon-small-shelter|omaloon-small-shelter-ui
#\uF8A6
63654=omaloon-pressure-source|omaloon-pressure-source-ui
#\uF8A5
63653=omaloon-landing-capsule|omaloon-landing-capsule-ui
#\uF8A4
63652=omaloon-cobalt|omaloon-cobalt-ui
#\uF8A3
63651=omaloon-nickel|omaloon-nickel-ui
#\uF8A2
63650=omaloon-composite|omaloon-composite-ui
#\uF8A1
63649=omaloon-magnetite|omaloon-magnetite-ui
#\uF8A0
63648=omaloon-glacium|omaloon-glacium-ui
#\uF89F
63647=omaloon-tired-glacium|omaloon-tired-glacium-ui
#\uF89E
63646=omaloon-discovery|omaloon-discovery-ui
#\uF89D
63645=omaloon-glacied|omaloon-glacied-ui
#\uF89C
63644=omaloon-wind-breeze|omaloon-wind-breeze-ui
#\uF89B
63643=omaloon-filled-with-water|omaloon-filled-with-water-ui
#\uF89A
63642=omaloon-filled-with-glacium|omaloon-filled-with-glacium-ui
#\uF899
63641=omaloon-filled-with-slag|omaloon-filled-with-slag-ui
#\uF898
63640=omaloon-filled-with-oil|omaloon-filled-with-oil-ui
#\uF897
63639=omaloon-glasmore|omaloon-glasmore-ui
#\uF896
63638=omaloon-pressure|omaloon-pressure-ui
#\uF895
63637=omaloon-purpura|omaloon-purpura-ui
#\uF894
63636=omaloon-settings|omaloon-settings-ui
#\uF893
63635=omaloon-apex|omaloon-apex-ui
#\uF892
63634=omaloon-convergence|omaloon-convergence-ui
