import arc.files.*
import arc.struct.*
import arc.util.io.*

sourceSets.main.java.srcDirs = ['src/']

dependencies{
    implementation project(':main')
    compileOnly project(':annotations')
    annotationProcessor project(':annotations')
    implementation "com.github.Anuken.Arc:arc-core:$arcVersion"
    implementation "com.github.Anuken.Mindustry:core:$mindustryVersion"
}

tasks.register('proc', JavaExec){
    dependsOn classes
    inputs.dir file('../main/assets-raw/sprites')
    outputs.dir file('../main/assets/sprites')

    workingDir = rootProject.ext.assetsDir
    mainClass = (rootProject.ext.modName as String).replace("-", "") + '.tools.Tools'
    classpath = sourceSets.main.runtimeClasspath
    systemProperty 'currentModName', rootProject.ext.modName

    doFirst{
        delete outputs.files
        copy{
            from inputs.files
            into outputs.files.singleFile
        }
    }
}

tasks.register('updateBundles'){
    def targetBundle = findProperty('bundle')
    doLast{
        def uniEscape = { String s ->
            s.collect{ c ->
                int code = c.codePointAt(0)
                (code > 61 && code < 127) ? (c == '\\' ? "\\\\" : c) :
                (code >= 0xE000 && code <= 0xF8FF) ? String.format("\\u%04x", code) : c
            }.join()
        }

        File bundlesDir = file("../main/assets/bundles")
        File baseBundleFile = new File(bundlesDir, "bundle.properties")
        if(!baseBundleFile.exists()) return

        OrderedMap<String, String> base = new OrderedMap<>()
        PropertiesUtils.load(base, Fi.get(baseBundleFile.absolutePath).reader())

        IntMap<String> comments = new IntMap<>()
        def lines = Fi.get(baseBundleFile.absolutePath).reader().readLines()
        int offset = 0
        lines.eachWithIndex{ line, i ->
            if(i > 0 && lines[i - 1].endsWith("\\")) offset++
            else if(line.isEmpty() || line.startsWith("#")) comments.put(i - offset, line)
        }

        Fi.get(bundlesDir.absolutePath).walk{ child ->
            if(child.name() == "bundle.properties" || child.path().contains("output")) return
            if(targetBundle && child.name() != targetBundle) return

            OrderedMap<String, String> other = new OrderedMap<>()
            PropertiesUtils.load(other, child.reader())

            for(String key : Seq.with(other.orderedKeys())){
                if(!base.containsKey(key)) other.remove(key)
            }
            for(String key : base.orderedKeys()){
                if(!other.get(key)?.trim()) other.put(key, base.get(key))
            }

            StringBuilder res = new StringBuilder()
            int i = 0
            for(String key : base.orderedKeys()){
                while(comments.containsKey(i++)) res.append(comments.get(i - 1)).append('\n')
                if(other.get(key) == null) continue
                def v = other.get(key)
                res.append(key).append(" =").append(v.trim() ? " " : "").append(uniEscape(v).replace("\n", "\\n")).append('\n')
            }
            child.writeString(res.toString())
        }
    }
}